### ISSUE TITLE
-break- error, with no other debugging context

### ISSUE THREAD

**Issue by adempewolff** [wbuchanan/StataJSON#38]
Hello,

I installed jsonio using `net inst jsonio, from(https://wbuchanan.github.io/StataJSON/) replace`

I'm trying to use it to import a bulk data file from the US Energy Information Administration ([this](http://api.eia.gov/bulk/INTL.zip) one, an example of first object in file is provided below).
```
{"series_id":"INTL.5-8-WORL-MMTCD.A","name":"Petroleum and other liquids CO2 emissions, World, Annual","units":"million metric tonnes carbon dioxide","f":"A","copyright":"None","source":"EIA, U.S. Energy Information Administration","geography":"WLD","start":"1949","end":"2018","last_updated":"2021-02-19T11:27:14-05:00","geoset_id":"INTL.5-8-MMTCD.A","data":[["2018",12796.519782790207],["2017",12702.478930196503],["2016",12555.46198138228],["2015",12381.430991439758],["2014",12153.628257822123],["2013",12025.7975126473],["2012",11893.536221594504],["2011",11723.149697568331],["2010",11593.702627336494],["2009",11279.832802108156],["2008",11370.841522899556],["2007",11090.87771889409],["2006",11434.960713595909],["2005",11376.761824738292],["2004",11199.061386249272],["2003",10818.80774928966],["2002",10621.284698564135],["2001",10527.368098651208],["2000",10436.564200165238],["1999",10313.839559805696],["1998",10121.926939191188],["1997",10056.286304771838],["1996",9847.611994974985],["1995",9654.998976411358],["1994",9515.198222088826],["1993",9353.01578884376],["1992",9331.53313779656],["1991",9310.426756545172],["1990",9276.904589164633],["1989",9220.63782978531],["1988",9079.439607481787],["1987",8842.652640653609],["1986",8702.149950706336],["1985",8349.152285154198],["1984",8355.000070483042],["1983",7720.600564410179],["1982",7797.476651724483],["1981",7991.229633735594],["1980",8396.756171438397],["1979",2455.243565],["1978",2539.512281],["1977",2493.85347],["1976",2364.614986],["1975",2202.114846],["1974",2240.609729],["1973",2339.645958],["1972",2218.906895],["1971",2056.179567],["1970",1982.516977],["1969",1900.962812],["1968",1810.467072],["1967",1700.584098],["1966",1635.40103],["1965",1559.077356],["1964",1495.143873],["1963",1459.446041],["1962",1421.790194],["1961",1368.764546],["1960",1348.642779],["1959",1306.825723],["1958",1256.210693],["1957",1218.098173],["1956",1218.049517],["1955",1174.738643],["1954",1080.801692],["1953",1064.970514],["1952",1024.84276],["1951",990.102419],["1950",917.619072],["1949",819.614615]]}
```
I try using the command:
`jsonio kv, file("path\to\file\INTL.json" elements("data") nourl`

But I simply get a `---Break---` error immediately.  Even with `set trace on` I don't get much more information.  The last line before the break is `javacall org.paces.Stata.Input.InJSON insheetFile args(`"my\filepath\NTL.json"' "data")`

Is there something wrong with the syntax I am using?  The structure of the .json I am trying to import?  Or is it possible that Stata is just failing to call the java library?

Thanks in advance for any help!

**Comment by wbuchanan** [comment]
@adempewolff 
Can you try adding

```
set debug on
set tracedepth 3
set trace on
```

Prior to running the command?  I'm hoping this might provide a bit more useful information that will be helpful for me to figure out what is going on.

**Comment by adempewolff** [comment]
I removed most of the filepaths, but left the very end of them as I noticed that one of the filepaths in the "Classpaths" section is to a different subfolder and file.  Any chance that there is a namespace conflict between a global macro I have already defined and something that jsonio expects to be undefined?


```
. jsonio kv, file("firstline

> secondline\data\USEIA\INTL.json") elements("data") nourl

-------------------------------------------------------------------------------------------- begin jsonio ---

- version 13.0

- syntax anything(name=subtype id="Input/Output Type") [if] [in] , [ ELEMents(passthru) noURL FILEnm(string)

> OBid(passthru) METAprint(passthru) What(passthru) STUBname(passthru) ]

- gettoken cmd opts : subtype

- if `"`url'"' == "nourl" loc filenm `: subinstr loc filenm `"~"' `"`: env HOME'"''

= if `"nourl"' == "nourl" loc filenm C:\Ufirstline

> secondline\data\USEIA\INTL.json

- if `"`cmd'"' == "kv" keyval `"`filenm'"', `elements' `url'

= if `"kv"' == "kv" keyval `"C:\firstline

>  secondline\data\USEIA\INTL.json"', elements("data") nourl

  ----------------------------------------------------------------------------------- begin jsonio.keyval ---

  - syntax anything(name=source id="Source of the JSON Input") [, ELEMents(string) noURL ]

  - if `"`elements'"' == "" loc elements ".*"

  = if `"data"' == "" loc elements ".*"

  - if `"`url'"' == "nourl" {

  = if `"nourl"' == "nourl" {

  - javacall org.paces.Stata.Input.InJSON insheetFile, args(`source' "`elements'")

  = javacall org.paces.Stata.Input.InJSON insheetFile, args(`"C:/firstline

> secondline\\data\USEIA\INTL.json"'

>  "data")

Classpaths:

    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/

    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/

    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libdeps-plugin.jar

    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libstata-plugin.jar

    file:/C:/firstline

    > secondline/data/WES/microdata/Sierra-Leone-2009-2017-panel-da

    > ta-/

    file:/C:/ado/plus/

    file:/C:/ado/plus/jar/

    file:/C:/ado/plus/jar/jsonio.jar

    file:/C:/ado/

    }

  ------------------------------------------------------------------------------------- end jsonio.keyval ---

---------------------------------------------------------------------------------------------- end jsonio ---

--Break--

r(1);
```

**Comment by adempewolff** [comment]
Hmm, that filepath seems to just be Stata's current working directory, so probably not the problem.

**Comment by adempewolff** [comment]
A couple more notes: those errors posted above occur while running Stata 15 on my work computer, which runs Windows 10.  I get a different set of errors (below) when using jsonio with Stata 16 on my personal computer, which runs Ubuntu 20.04.  I can't tell whether this is perhaps just capturing more from the same errors, or whether it is a completely different issue, but I'll provide it in case it is helpful.

```
. jsonio kv, file("/media/austin/data/desktop/eia_intl/INTL.json") elements("data") nourl
---------------------------------------------------------------------------------------------------- begin jsonio ---
- version 13.0
- syntax anything(name=subtype id="Input/Output Type") [if] [in] , [ ELEMents(passthru) noURL FILEnm(string) OBid(pas
> sthru) METAprint(passthru) What(passthru) STUBname(passthru) ]
- gettoken cmd opts : subtype
- if `"`url'"' == "nourl" loc filenm `: subinstr loc filenm `"~"' `"`: env HOME'"''
= if `"nourl"' == "nourl" loc filenm /media/austin/data/desktop/eia_intl/INTL.json
- if `"`cmd'"' == "kv" keyval `"`filenm'"', `elements' `url'
= if `"kv"' == "kv" keyval `"/media/austin/data/desktop/eia_intl/INTL.json"', elements("data") nourl
  ------------------------------------------------------------------------------------------- begin jsonio.keyval ---
  - syntax anything(name=source id="Source of the JSON Input") [, ELEMents(string) noURL ]
  - if `"`elements'"' == "" loc elements ".*"
  = if `"data"' == "" loc elements ".*"
  - if `"`url'"' == "nourl" {
  = if `"nourl"' == "nourl" {
  - javacall org.paces.Stata.Input.InJSON insheetFile, args(`source' "`elements'")
  = javacall org.paces.Stata.Input.InJSON insheetFile, args(`"/media/austin/data/desktop/eia_intl/INTL.json"' "data")
Classpaths:
    file:/usr/local/stata16/ado/base/
    file:/usr/local/stata16/ado/base/jar/
    file:/usr/local/stata16/ado/base/jar/libstata-plugin.jar
    file:/usr/local/stata16/ado/base/jar/libdeps-plugin.jar
    file:/usr/local/stata16/utilities/java/linux-x64/zulu-jre11.0.9/lib/
    file:/home/austin/ado/plus/
    file:/home/austin/ado/plus/jar/
    file:/home/austin/ado/plus/jar/jsonio.jar
    file:/home/austin/ado/
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.stata.Javacall.load(Javacall.java:130)
        at com.stata.Javacall.load(Javacall.java:90)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:121)
        at org.paces.Stata.Input.InJSON.insheetFile(InJSON.java:155)
        ... 6 more
    }
  --------------------------------------------------------------------------------------------- end jsonio.keyval ---
------------------------------------------------------------------------------------------------------ end jsonio ---
r(5100);
```

**Comment by wbuchanan** [comment]
@adempewolff 
Do you have StataJavaUtilities installed on your Linux box?  The first few error messages tend to happen when that jar isn't available on the classpath.  https://github.com/wbuchanan/StataJavaUtilities.

Some of the internal methods in the libraries use Java's reflections methods to determine which methods to dispatch.

**Comment by adempewolff** [comment]
I do not have that installed, what's the best installation option for it?  I can't seem to get `net install` to do the trick, do I just download the `javautils.ado` from that repository manually and throw it in my user ado directory?

I confess complete ignorance of how the stata calls java  My original assumption was that it would just use the system jre--and that maybe that wasn't configured correctly, but after a closer look, it seems to ship with it's own jre.

```
. java query
---------------------------------------------------------------------------------------------------------------------
    Java settings
      set java_heapmax     2048m
      set java_home        /usr/local/stata16/utilities/java/linux-x64/zulu-jre11.0.9/

    Java system information
      initialized          yes
      heap usage           28m
      heap committed       498m
      runtime vendor       Azul Systems, Inc.
      runtime version      11.0.9+11-LTS
      system classpath     /usr/local/stata16/utilities/jar/sfi-api.jar:/usr/local/stata16/utilities/jar/libstata-cor
> e.jar:/usr/local/stata16/utilities/jar/libdeps-core.jar:/usr/local/stata16/utilities/jar/aspose-words-18.11-jdk16.j
> ar:
      javacall classpath   /usr/local/stata16/ado/base:/usr/local/stata16/ado/base/jar:/usr/local/stata16/ado/base/ja
> r/libstata-plugin.jar:/usr/local/stata16/ado/base/jar/libdeps-plugin.jar:/usr/local/stata16/utilities/java/linux-x6
> 4/zulu-jre11.0.9/lib:/home/austin/ado/plus:/home/austin/ado/plus/jar:/home/austin/ado/plus/jar/jsonio.jar:/home/aus
> tin/ado
      library path         /usr/local/stata16/utilities/java/linux-x64/zulu-jre11.0.9/lib/server/libjvm.so
```

**Comment by adempewolff** [comment]
The original mysterious `---Break---` was my fault.  I forgot that on windows when you rename a file using explorer, it doesn't not replace the original file extension.  So I thought I had renamed the file to `INTL.json` when it was in fact now `INTL.json.txt`.

That said, I'm still getting errors trying to read in the file, both before and after downloading `StataJavaUtilities.jar` and putting it into my ado path.

Before manually downloading `StataJavaUtilities.jar` :

```
jsonio kv, file("$test") nourl elements("data")
Classpaths:
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libdeps-plugin.jar
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libstata-plugin.jar
    file:/C:/Users/dempewolffaj/OneDrive%20-%20Millennium%20Challenge%20Corporati
    > on/Documents/
    file:/C:/ado/plus/
    file:/C:/ado/plus/jar/
    file:/C:/ado/plus/jar/jsonio.jar
    file:/C:/ado/
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
> a:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
> Impl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.stata.Javacall.load(Javacall.java:130)
        at com.stata.Javacall.load(Javacall.java:90)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:121)
        at org.paces.Stata.Input.InJSON.insheetFile(InJSON.java:155)
        ... 6 more
r(5100);
```

After downloading `StataJavaUtilities.jar` (from [here](https://github.com/wbuchanan/StataJavaUtilities/blob/master/target/StataJavaUtilities.jar)).

```
jsonio kv, file("$test") nourl elements("data")
Classpaths:
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libdeps-plugin.jar
    file:/C:/Program%20Files%20(x86)/Stata15/ado/base/jar/libstata-plugin.jar
    file:/C:/Users/dempewolffaj/OneDrive%20-%20Millennium%20Challenge%20Corporati
    > on/Documents/
    file:/C:/ado/plus/
    file:/C:/ado/plus/jar/
    file:/C:/ado/plus/jar/jsonio.jar
    file:/C:/ado/plus/jar/StataJavaUtilities.jar
    file:/C:/ado/
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
> a:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
> Impl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.stata.Javacall.load(Javacall.java:130)
        at com.stata.Javacall.load(Javacall.java:90)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:199)
        at org.paces.Stata.Input.FlatJSON.flatten(FlatJSON.java:121)
        at org.paces.Stata.Input.InJSON.insheetFile(InJSON.java:155)
        ... 6 more
r(5100);
```

Interestingly, `insheetjson` seems to work to some extent, I just can't find any documentation on how to use it with hybrid table structures, whereas `jsonio` seems to have this nice default behavior of just flattening everything to key value pairs that I can sort out myself with regex expression.

**Comment by wbuchanan** [comment]
@adempewolff 
Are you able to share a copy of the file you are trying to read/parse?  The exception that is being thrown is making me think there might be part of the file that doesn't completely conform with the JSON specification.

**Comment by adempewolff** [comment]
Sure, it's a public dataset: [http://api.eia.gov/bulk/INTL.zip](http://api.eia.gov/bulk/INTL.zip).

That's a pretty large file though, so I've also uploaded a copy with only the first few objects.

[INTL_firstfew.txt](https://github.com/wbuchanan/StataJSON/files/6135845/INTL_firstfew.txt)

The data I want to extract is in a nested array of year-value pairs, which seems to be a bit different than other examples I've seen. 

```
"data":[["2018",12796.519782790207],["2017",12702.478930196503],["2016",12555.46198138228],["2015",12381.430991439758],["2014",12153.628257822123],["2013",12025.7975126473],["2012",11893.536221594504],["2011",11723.149697568331],["2010",11593.702627336494],["2009",11279.832802108156],["2008",11370.841522899556],["2007",11090.87771889409],["2006",11434.960713595909],["2005",11376.761824738292],["2004",11199.061386249272],["2003",10818.80774928966],["2002",10621.284698564135],["2001",10527.368098651208],["2000",10436.564200165238],["1999",10313.839559805696],["1998",10121.926939191188],["1997",10056.286304771838],["1996",9847.611994974985],["1995",9654.998976411358],["1994",9515.198222088826],["1993",9353.01578884376],["1992",9331.53313779656],["1991",9310.426756545172],["1990",9276.904589164633],["1989",9220.63782978531],["1988",9079.439607481787],["1987",8842.652640653609],["1986",8702.149950706336],["1985",8349.152285154198],["1984",8355.000070483042],["1983",7720.600564410179],["1982",7797.476651724483],["1981",7991.229633735594],["1980",8396.756171438397],["1979",2455.243565],["1978",2539.512281],["1977",2493.85347],["1976",2364.614986],["1975",2202.114846],["1974",2240.609729],["1973",2339.645958],["1972",2218.906895],["1971",2056.179567],["1970",1982.516977],["1969",1900.962812],["1968",1810.467072],["1967",1700.584098],["1966",1635.40103],["1965",1559.077356],["1964",1495.143873],["1963",1459.446041],["1962",1421.790194],["1961",1368.764546],["1960",1348.642779],["1959",1306.825723],["1958",1256.210693],["1957",1218.098173],["1956",1218.049517],["1955",1174.738643],["1954",1080.801692],["1953",1064.970514],["1952",1024.84276],["1951",990.102419],["1950",917.619072],["1949",819.614615]]
```

**Comment by adempewolff** [comment]
Thank you very much for your responsiveness to my issues.  If you want to continue trying to debug this issue, I'm happy to continue providing information and testing things as needed.  However, I ended up just using `infix` and regex commands to parse things manually, so I no longer need to get this working on my computer and with this file.

**Comment by wbuchanan** [comment]
@adempewolff 
I think I may have figured out what the problem is.  I've copied/pasted the first two objects from the file at the link you shared previously below to illustrate:

```
{"series_id":"INTL.5-8-WORL-MMTCD.A","name":"Petroleum and other liquids CO2 emissions, World, Annual","units":"million metric tonnes carbon dioxide","f":"A","copyright":"None","source":"EIA, U.S. Energy Information Administration","geography":"WLD","start":"1949","end":"2018","last_updated":"2021-02-19T11:27:14-05:00","geoset_id":"INTL.5-8-MMTCD.A","data":[["2018",12796.519782790207],["2017",12702.478930196503],["2016",12555.46198138228],["2015",12381.430991439758],["2014",12153.628257822123],["2013",12025.7975126473],["2012",11893.536221594504],["2011",11723.149697568331],["2010",11593.702627336494],["2009",11279.832802108156],["2008",11370.841522899556],["2007",11090.87771889409],["2006",11434.960713595909],["2005",11376.761824738292],["2004",11199.061386249272],["2003",10818.80774928966],["2002",10621.284698564135],["2001",10527.368098651208],["2000",10436.564200165238],["1999",10313.839559805696],["1998",10121.926939191188],["1997",10056.286304771838],["1996",9847.611994974985],["1995",9654.998976411358],["1994",9515.198222088826],["1993",9353.01578884376],["1992",9331.53313779656],["1991",9310.426756545172],["1990",9276.904589164633],["1989",9220.63782978531],["1988",9079.439607481787],["1987",8842.652640653609],["1986",8702.149950706336],["1985",8349.152285154198],["1984",8355.000070483042],["1983",7720.600564410179],["1982",7797.476651724483],["1981",7991.229633735594],["1980",8396.756171438397],["1979",2455.243565],["1978",2539.512281],["1977",2493.85347],["1976",2364.614986],["1975",2202.114846],["1974",2240.609729],["1973",2339.645958],["1972",2218.906895],["1971",2056.179567],["1970",1982.516977],["1969",1900.962812],["1968",1810.467072],["1967",1700.584098],["1966",1635.40103],["1965",1559.077356],["1964",1495.143873],["1963",1459.446041],["1962",1421.790194],["1961",1368.764546],["1960",1348.642779],["1959",1306.825723],["1958",1256.210693],["1957",1218.098173],["1956",1218.049517],["1955",1174.738643],["1954",1080.801692],["1953",1064.970514],["1952",1024.84276],["1951",990.102419],["1950",917.619072],["1949",819.614615]]}
{"series_id":"INTL.1-8-OPEC-MMTCD.A","name":"Coal and coke CO2 emissions, OPEC, Annual","units":"million metric tonnes carbon dioxide","f":"A","copyright":"None","source":"EIA, U.S. Energy Information Administration","geography":"AGO+ARE+COG+DZA+GAB+GNQ+IRN+IRQ+KWT+LBY+NGA+SAU+VEN","start":"1980","end":"2018","last_updated":"2021-02-19T11:27:14-05:00","geoset_id":"INTL.1-8-MMTCD.A","data":[["2018",14.892804473834827],["2017",14.655737825691554],["2016",13.944523922588756],["2015",13.906998867782583],["2014",15.45122680115308],["2013",15.73533215357278],["2012",14.290704175215353],["2011",12.935467214672713],["2010",10.584413893160349],["2009",9.674640134547165],["2008",9.317571590614445],["2007",9.33175653155159],["2006",8.777699563517045],["2005",9.307802617542771],["2004",8.14256658890443],["2003",7.6288053560901625],["2002",7.107990970465125],["2001",7.66684096131898],["2000",7.545627994230137],["1999",7.355474273810265],["1998",7.247098655215215],["1997",6.895031092422024],["1996",6.373578148255441],["1995",6.0283343626553565],["1994",7.1449446585403065],["1993",6.960909257392298],["1992",6.933066797061391],["1991",7.705996822221036],["1990",6.661279229259055],["1989",6.966718227576964],["1988",8.075019843251987],["1987",8.078122001082535],["1986",8.12503423650602],["1985",8.081779955666816],["1984",7.906406017601295],["1983",8.930720886618612],["1982",7.854139318091077],["1981",5.685616299941554],["1980",5.940159908678087]]}
```

The issue here is that the file does not contain valid JSON.  In the [JSON Specification](https://www.json.org/json-en.html), objects are required to be delimited by a comma.  In the side bar on the right hand side of the page you can see the grammatical rules:

```
json
    element

value
    object
    array
    string
    number
    "true"
    "false"
    "null"

object
    '{' ws '}'
    '{' members '}'

members
    member
    member ', ' members
```

The last line copied here is what is causing the issue.  Instead of delimiting the members using a comma there is a new line character inserted following the `}` that ends the first object.  From the perspective of the underlying parser, this ends up being problematic since it was written to follow the RFC explicitly.  That said, there is a Python library `jsonlines` which is developed precisely to parse files formatted in this specific way.  You could potentially read the data using that library and output a properly formed JSON object, or could parse it entirely using that library and Pandas.  Hopefully this helps explain things a bit.

**Comment by adempewolff** [comment]
Thanks for looking into it.  They claim to be JSON compliant, but that probably refers to results from individual API calls. I'm guessing whoever prepared these bulk download files just concatenated individual objects in whatever manner made the most sense to them.

I'm guessing I could use `-filefilter-` to replace the returns with commas and make it JSON compliant.  Coincidentally, the carriage returns between objects instead of commas is exactly what made it so easy for me to manually parse using `-infix-`.

Thanks for the recommendation about the Python library.  Unfortunately, I'm not able to use Python (or pretty much anything other than Stata) on my work computer.  Luckily, manual parsing ended up being easy and fast in this instance.  
e.g.
```
infix strL line 1-40000 using "$eia_intl_data", clear

gen series_id = regexs(2) if(regexm(line, `"("series_id":")([^"]+)(")"'))

gen data = regexs(2) if(regexm(line, `"("data":)([^}]+)(})"'))

forvalues year = 1949/2021 {

	display "processing data for year: `year'"
	gen value`year' = real(regexs(2)) ///
						if(regexm(data, `"("`year'",)([0-9\.]+)(])"'))

}
```

The overwhelming majority of my time on this was spent figuring out how to avoid or reduce the scope of native `-reshape-` commands at all costs--which I think I would need to do with a purpose built json parser anyway (I can't use the binary blobs from the `gtools` plugin unfortunately) .

Thanks again, for both your help with this issue and creating the tool in the first place!

**Comment by wbuchanan** [comment]
@adempewolff 
If you have access to a *nix command line, it may be better to use `sed` instead of `filefilter`.  New line characters are allowed in string values of JSON, so you would specifically want to replace \}\n\{ with \}, \{.  That way any new lines embedded in strings are properly preserved.  `sed` is also fairly fast as well.
